# Set this to the interface facing the public network
no-dhcp-interface=eth0

# Define a range
dhcp-range=family,10.10.10.200,10.10.10.253,255.255.255.0,24h

# Set the NTP time server address to be the same machine as
# is running dnsmasq
#dhcp-option=42,0.0.0.0
dhcp-option=family,3,10.10.10.1

dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# Log lots of extra information about DHCP transactions.
log-dhcp