//go:build unit

/*
(c) Copyright 2026 Eric Paul Forgette

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package wireguard

import (
	"testing"
)

func TestRenderClientConf(t *testing.T) {
	t.Parallel()

	d := clientConfData{
		Name:             "alice",
		GeneratedDate:    "2026-05-31",
		ClientPrivateKey: "CLIENTPRIVKEYBASE64=",
		ClientAddress:    "192.168.192.2/24",
		DNS:              "192.168.192.1",
		ServerPublicKey:  "SERVERPUBKEYBASE64=",
		Endpoint:         "home.example.org:51820",
		AllowedIPs:       "0.0.0.0/0, ::/0",
		Keepalive:        25,
	}

	want := `# pirewall WireGuard client config for alice
# Generated 2026-05-31 by ` + "`pirewall -wg-add-client=alice`" + `

[Interface]
PrivateKey = CLIENTPRIVKEYBASE64=
Address = 192.168.192.2/24
DNS = 192.168.192.1

[Peer]
PublicKey = SERVERPUBKEYBASE64=
Endpoint = home.example.org:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
`

	got := renderClientConf(d)
	if got != want {
		t.Errorf("render mismatch:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestRenderServerConf_NoPeers(t *testing.T) {
	t.Parallel()

	s := &serverConf{
		Endpoint:   "home.example.org:51820",
		Address:    "192.168.192.1/24",
		ListenPort: 51820,
		PrivateKey: "SERVERPRIVKEYBASE64=",
	}

	want := `# pirewall WireGuard server
# Generated by ` + "`pirewall -wireguard`" + `. The Endpoint comment below is read by
# ` + "`pirewall -wg-add-client`" + ` to populate client configs. Peer blocks below
# are managed by pirewall — DO NOT hand-edit peer entries.
#
# Endpoint = home.example.org:51820

[Interface]
Address = 192.168.192.1/24
ListenPort = 51820
PrivateKey = SERVERPRIVKEYBASE64=
`

	got := renderServerConf(s)
	if got != want {
		t.Errorf("render mismatch:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}

func TestRenderServerConf_WithPeers(t *testing.T) {
	t.Parallel()

	s := &serverConf{
		Endpoint:   "home.example.org:51820",
		Address:    "192.168.192.1/24",
		ListenPort: 51820,
		PrivateKey: "SERVERPRIVKEYBASE64=",
		Peers: []peerEntry{
			{
				Name:       "alice",
				AddedDate:  "2026-05-31",
				PublicKey:  "ALICEPUBKEY=",
				AllowedIPs: "192.168.192.2/32",
			},
			{
				Name:       "bob",
				AddedDate:  "2026-06-01",
				PublicKey:  "BOBPUBKEY=",
				AllowedIPs: "192.168.192.3/32",
			},
		},
	}

	want := `# pirewall WireGuard server
# Generated by ` + "`pirewall -wireguard`" + `. The Endpoint comment below is read by
# ` + "`pirewall -wg-add-client`" + ` to populate client configs. Peer blocks below
# are managed by pirewall — DO NOT hand-edit peer entries.
#
# Endpoint = home.example.org:51820

[Interface]
Address = 192.168.192.1/24
ListenPort = 51820
PrivateKey = SERVERPRIVKEYBASE64=

# Peer: alice (added 2026-05-31)
[Peer]
PublicKey = ALICEPUBKEY=
AllowedIPs = 192.168.192.2/32

# Peer: bob (added 2026-06-01)
[Peer]
PublicKey = BOBPUBKEY=
AllowedIPs = 192.168.192.3/32
`

	got := renderServerConf(s)
	if got != want {
		t.Errorf("render mismatch:\n--- got ---\n%s--- want ---\n%s", got, want)
	}
}
