/*
(c) Copyright 2026 Eric Paul Forgette

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package wireguard

import (
	"fmt"
	"strings"
)

// clientConfData is the input to renderClientConf. All fields are required.
type clientConfData struct {
	Name             string
	GeneratedDate    string // YYYY-MM-DD
	ClientPrivateKey string
	ClientAddress    string // e.g. "192.168.192.2/24"
	DNS              string
	ServerPublicKey  string
	Endpoint         string
	AllowedIPs       string
	Keepalive        int
}

// renderServerConf returns the exact body of /etc/wireguard/wg0.conf for s.
// Empty Peers yields a file with no peer blocks (server-only).
func renderServerConf(s *serverConf) string {
	var b strings.Builder

	b.WriteString("# pirewall WireGuard server\n")
	b.WriteString("# Generated by `pirewall -wireguard`. The Endpoint comment below is read by\n")
	b.WriteString("# `pirewall -wg-add-client` to populate client configs. Peer blocks below\n")
	b.WriteString("# are managed by pirewall — DO NOT hand-edit peer entries.\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Endpoint = %s\n", s.Endpoint)
	b.WriteString("\n")
	b.WriteString("[Interface]\n")
	fmt.Fprintf(&b, "Address = %s\n", s.Address)
	fmt.Fprintf(&b, "ListenPort = %d\n", s.ListenPort)
	fmt.Fprintf(&b, "PrivateKey = %s\n", s.PrivateKey)

	for _, p := range s.Peers {
		b.WriteString("\n")
		fmt.Fprintf(&b, "# Peer: %s (added %s)\n", p.Name, p.AddedDate)
		b.WriteString("[Peer]\n")
		fmt.Fprintf(&b, "PublicKey = %s\n", p.PublicKey)
		fmt.Fprintf(&b, "AllowedIPs = %s\n", p.AllowedIPs)
	}

	return b.String()
}

// renderClientConf returns the exact body of /etc/wireguard/clients/<name>.conf
// for d.
func renderClientConf(d clientConfData) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# pirewall WireGuard client config for %s\n", d.Name)
	fmt.Fprintf(&b, "# Generated %s by `pirewall -wg-add-client=%s`\n", d.GeneratedDate, d.Name)
	b.WriteString("\n")
	b.WriteString("[Interface]\n")
	fmt.Fprintf(&b, "PrivateKey = %s\n", d.ClientPrivateKey)
	fmt.Fprintf(&b, "Address = %s\n", d.ClientAddress)
	fmt.Fprintf(&b, "DNS = %s\n", d.DNS)
	b.WriteString("\n")
	b.WriteString("[Peer]\n")
	fmt.Fprintf(&b, "PublicKey = %s\n", d.ServerPublicKey)
	fmt.Fprintf(&b, "Endpoint = %s\n", d.Endpoint)
	fmt.Fprintf(&b, "AllowedIPs = %s\n", d.AllowedIPs)
	fmt.Fprintf(&b, "PersistentKeepalive = %d\n", d.Keepalive)

	return b.String()
}
